// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUL3Z-feGkri7T5uRObmM5DVKbXQDN4-s',
    appId: '1:422999707038:web:a0d59ab035adbca6ba9a8f',
    messagingSenderId: '422999707038',
    projectId: 'me-good-2575b',
    authDomain: 'me-good-2575b.firebaseapp.com',
    storageBucket: 'me-good-2575b.appspot.com',
    measurementId: 'G-L51SH83VT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_60hQ4Z830B4gcJvz17MadIrvr2q2I6c',
    appId: '1:422999707038:android:7156f58abc62c2d3ba9a8f',
    messagingSenderId: '422999707038',
    projectId: 'me-good-2575b',
    storageBucket: 'me-good-2575b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ZmnYn5K_Cv1S0JFZICC-9ZMcfCz4DPM',
    appId: '1:422999707038:ios:dc9656507b983a38ba9a8f',
    messagingSenderId: '422999707038',
    projectId: 'me-good-2575b',
    storageBucket: 'me-good-2575b.appspot.com',
    iosClientId: '422999707038-g7gkns7cupqc7n458uu1q1r7p9rs9mpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.meGood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3ZmnYn5K_Cv1S0JFZICC-9ZMcfCz4DPM',
    appId: '1:422999707038:ios:35eb4c586485358fba9a8f',
    messagingSenderId: '422999707038',
    projectId: 'me-good-2575b',
    storageBucket: 'me-good-2575b.appspot.com',
    iosClientId: '422999707038-pjg1c6grc14l8mq60odu96o8cba70la8.apps.googleusercontent.com',
    iosBundleId: 'com.example.meGood.RunnerTests',
  );
}
